//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMServer.LicWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInfo", Namespace="http://schemas.datacontract.org/2004/07/LicWebService")]
    [System.SerializableAttribute()]
    public partial class ProductInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HdModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HdSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MacAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProdDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsbInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationCode {
            get {
                return this.ActivationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivationCodeField, value) != true)) {
                    this.ActivationCodeField = value;
                    this.RaisePropertyChanged("ActivationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CpuId {
            get {
                return this.CpuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CpuIdField, value) != true)) {
                    this.CpuIdField = value;
                    this.RaisePropertyChanged("CpuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HdModel {
            get {
                return this.HdModelField;
            }
            set {
                if ((object.ReferenceEquals(this.HdModelField, value) != true)) {
                    this.HdModelField = value;
                    this.RaisePropertyChanged("HdModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HdSerial {
            get {
                return this.HdSerialField;
            }
            set {
                if ((object.ReferenceEquals(this.HdSerialField, value) != true)) {
                    this.HdSerialField = value;
                    this.RaisePropertyChanged("HdSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MacAddr {
            get {
                return this.MacAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.MacAddrField, value) != true)) {
                    this.MacAddrField = value;
                    this.RaisePropertyChanged("MacAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProdDate {
            get {
                return this.ProdDateField;
            }
            set {
                if ((this.ProdDateField.Equals(value) != true)) {
                    this.ProdDateField = value;
                    this.RaisePropertyChanged("ProdDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdName {
            get {
                return this.ProdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdNameField, value) != true)) {
                    this.ProdNameField = value;
                    this.RaisePropertyChanged("ProdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdSerial {
            get {
                return this.ProdSerialField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdSerialField, value) != true)) {
                    this.ProdSerialField = value;
                    this.RaisePropertyChanged("ProdSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdVersion {
            get {
                return this.ProdVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdVersionField, value) != true)) {
                    this.ProdVersionField = value;
                    this.RaisePropertyChanged("ProdVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsbInfo {
            get {
                return this.UsbInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsbInfoField, value) != true)) {
                    this.UsbInfoField = value;
                    this.RaisePropertyChanged("UsbInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivationInfo", Namespace="http://schemas.datacontract.org/2004/07/LicWebService")]
    [System.SerializableAttribute()]
    public partial class ActivationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivateDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ProdDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivateDesc {
            get {
                return this.ActivateDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivateDescField, value) != true)) {
                    this.ActivateDescField = value;
                    this.RaisePropertyChanged("ActivateDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivationCode {
            get {
                return this.ActivationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivationCodeField, value) != true)) {
                    this.ActivationCodeField = value;
                    this.RaisePropertyChanged("ActivationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActivated {
            get {
                return this.IsActivatedField;
            }
            set {
                if ((this.IsActivatedField.Equals(value) != true)) {
                    this.IsActivatedField = value;
                    this.RaisePropertyChanged("IsActivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProdDate {
            get {
                return this.ProdDateField;
            }
            set {
                if ((this.ProdDateField.Equals(value) != true)) {
                    this.ProdDateField = value;
                    this.RaisePropertyChanged("ProdDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdName {
            get {
                return this.ProdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdNameField, value) != true)) {
                    this.ProdNameField = value;
                    this.RaisePropertyChanged("ProdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdVersion {
            get {
                return this.ProdVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdVersionField, value) != true)) {
                    this.ProdVersionField = value;
                    this.RaisePropertyChanged("ProdVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LicWebService.ILicService")]
    public interface ILicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicService/LicRequestFirst", ReplyAction="http://tempuri.org/ILicService/LicRequestFirstResponse")]
        bool LicRequestFirst(out string retMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicService/LicRequestActivation", ReplyAction="http://tempuri.org/ILicService/LicRequestActivationResponse")]
        bool LicRequestActivation(out INMServer.LicWebService.ActivationInfo actInfo, INMServer.LicWebService.ProductInfo prodInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicService/LicCheckActivationState", ReplyAction="http://tempuri.org/ILicService/LicCheckActivationStateResponse")]
        bool LicCheckActivationState(out INMServer.LicWebService.ActivationInfo actInfo, INMServer.LicWebService.ProductInfo prodInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILicServiceChannel : INMServer.LicWebService.ILicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicServiceClient : System.ServiceModel.ClientBase<INMServer.LicWebService.ILicService>, INMServer.LicWebService.ILicService {
        
        public LicServiceClient() {
        }
        
        public LicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LicRequestFirst(out string retMsg) {
            return base.Channel.LicRequestFirst(out retMsg);
        }
        
        public bool LicRequestActivation(out INMServer.LicWebService.ActivationInfo actInfo, INMServer.LicWebService.ProductInfo prodInfo) {
            return base.Channel.LicRequestActivation(out actInfo, prodInfo);
        }
        
        public bool LicCheckActivationState(out INMServer.LicWebService.ActivationInfo actInfo, INMServer.LicWebService.ProductInfo prodInfo) {
            return base.Channel.LicCheckActivationState(out actInfo, prodInfo);
        }
    }
}
